version: "3"

services:
  api:
    image: api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - fiverrr
    volumes:
      - ./api/:/usr/src/app
      - /usr/src/app/node_modules

  web:
    image: web
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      - fiverrr
    depends_on:
      - api
    volumes:
      - ./web/:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - fiverrr
    volumes:
      - mongo-data:/data/db

networks:
  fiverrr:
    driver: bridge

volumes:
  mongo-data:
    driver: local
